### ISSUE TITLE
nuts.wad with fast monsters problems

### ISSUE THREAD

**Issue by despoa** [atsb/rzdoom#6]
By running nuts.wad with sv_fastmonsters set to 1 and god mode and letting projectiles very quickly accumulate, RZDoom will crash half the time and automatically close. This has never happened with the latest version of ZDoom before it was discontinued. Another consequence of having thousands of monsters is that sounds frequently cancel out over each other to the point where not many sounds actually play. This has also never happened in ZDoom and while it happens in Chocolate Doom, it's not to this extent. And if you pause the game a few dozens of seconds into playing nuts.wad, the music completely stops playing until the audio engine is manually restarted.

**Comment by atsb** [comment]
[rzdoom-openal.zip](https://github.com/atsb/rzdoom/files/9371397/rzdoom-openal.zip)

I'm uploading a very alpha build of OpenAL support.  Windows 64bit only.  When first starting, 'Sound System' will be default, you'll need to change it to MS WaveSynth or OPL etc...  to get OpenAL Music / Sound.  That's how it was in ZDoom also (except ZDoom never provided OpenAL builds officially, only FMOD EX).

From my testing.  The sound cutoff does not happen anymore and fastmonsters on nuts.wad with a load of missiles (I ran around for 30 seconds to gather them up) did not crash for me either.

**Comment by atsb** [comment]
OpenAL will have to be revisited another time.  Several important mods kept cutting off and sometimes crashing (Brutal Doom) for example, with OpenAL sound implementation.  I'll see about the crash in nuts.wad with the tracers but for now, FMOD will have to stay.
